### PR TITLE
Autoplay

### PR DESCRIPTION
**Pull request by johnbender**
Support `data-autoplay="N"` where `N` is a natural number representing the millisecond delay before advancing the slides.

### CODE REVIEW

**Comment by johnbender** [comment]
@scottjehl 

You may want to double check that I covered all the user interactions which should stop the autoplay.

**Comment by toddparker** [comment]
@johnbender - is there a preview URL for this PR?

**Comment by johnbender** [comment]
@toddparker 

I didn't think there was but I was wrong!

http://autoplay.origin.snapper.fgview.com/demo/

Second demo down on the page.

**Comment by toddparker** [comment]
@johnbender - demo looks good but I think we need to also pause it it you swipe to advance. I think there is an event you can tie into for that

**Pull request merged**
